name: Build and Push Docker Image

on:
  push:
    branches: 
      - main  # Trigger the workflow on push events to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract Python version
      id: python-version
      run: echo "::set-output name=version::$(grep FROM Dockerfile | cut -d':' -f2)"

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: negimeister/obs-auto-rtmp:${{ steps.python-version.outputs.version }}
